# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "master"   => {"memory" => "2048", "cpu" => "2", "ip" => "10", "image" => "generic/ubuntu2204"},
  "node01"   => {"memory" => "2048", "cpu" => "2", "ip" => "11", "image" => "generic/ubuntu2024"},
  "node02"   => {"memory" => "2048", "cpu" => "2", "ip" => "12", "image" => "generic/ubuntu2024"},
  "registry" => {"memory" => "2048", "cpu" => "2", "ip" => "20", "image" => "generic/ubuntu2024"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.jmsalles.casa"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
      
      # Sincronize o diretório atual do host com a VM
      machine.vm.synced_folder ".", "/vagrant", type: "rsync"

      # Configuração para o provider libvirt
      machine.vm.provider "libvirt" do |libvirt|
        libvirt.memory = conf["memory"].to_i
        libvirt.cpus = conf["cpu"].to_i
        libvirt.storage_pool_name = "default" # Ajuste conforme necessário
        #libvirt.volume_cache = "none"
        libvirt.disk_driver :cache => "none"
      end

      # Provisão com scripts
      machine.vm.provision "shell", path: "provision.sh"
      machine.vm.provision "shell", inline: "hostnamectl set-hostname #{name}.jmsalles.casa"
    end
  end
end
