
- name: Configuração Básica de Servidores
  hosts: all
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - vim
