---
- name: Instalar GLPI Agent
  hosts: all
    #  become: yes
  vars:
    glpi_agent_url: "https://github.com/glpi-project/glpi-agent/releases/download/1.11/glpi-agent-1.11-linux-installer.pl"
    glpi_server_url: "https://endereco_servidor_glpi"
    installer_path: "/tmp/glpi-agent-installer.pl"

  tasks:
    - name: Instalar dependências para HTTPS (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - curl
          - perl
          - ca-certificates
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Instalar dependências para HTTPS (Rocky/Red Hat)
      ansible.builtin.yum:
        name:
          - curl
          - perl
          - ca-certificates
        state: present
      when: ansible_os_family == "RedHat"

    - name: Baixar o instalador do GLPI Agent usando curl
      ansible.builtin.command:
        cmd: "curl -L {{ glpi_agent_url }} -o {{ installer_path }}"
      register: download_status

    - name: Verificar se o instalador foi baixado
      ansible.builtin.stat:
        path: "{{ installer_path }}"
      register: installer_stat

    - name: Falhar se o instalador não foi baixado
      ansible.builtin.fail:
        msg: "O instalador do GLPI Agent não foi baixado!"
      when: not installer_stat.stat.exists

    - name: Executar o instalador do GLPI Agent
      ansible.builtin.shell: |
        perl {{ installer_path }} --server {{ glpi_server_url }}
      args:
        executable: /bin/bash

    - name: Verificar se o GLPI Agent está instalado
      ansible.builtin.command:
        cmd: "glpi-agent --version"
      register: glpi_version
      failed_when: "'GLPI Agent' not in glpi_version.stdout"

    - name: Executar o GLPI Agent manualmente
      ansible.builtin.shell: |
        glpi-agent
      args:
        executable: /bin/bash

    - name: Validar inventário do GLPI Agent
      ansible.builtin.shell: |
        glpi-agent --debug
      register: inventory_status
      args:
        executable: /bin/bash

    - name: Exibir resultado da validação do inventário
      ansible.builtin.debug:
        msg: "Resultado da validação do inventário: {{ inventory_status.stdout }}"

