# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "master"   => {"memory" => "2048", "cpu" => "2", "ip" => "10", "image" => "ubuntu/focal64"},
  "node01"   => {"memory" => "2048", "cpu" => "2", "ip" => "11", "image" => "ubuntu/focal64"},
  "node02"   => {"memory" => "2048", "cpu" => "2", "ip" => "12", "image" => "ubuntu/focal64"},
  "registry" => {"memory" => "2048", "cpu" => "2", "ip" => "20", "image" => "ubuntu/focal64"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.jmsalles.casa"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/jmsalles-DCA"]
      end
      machine.vm.provision "shell", path: "provision.sh"
      machine.vm.provision "shell", inline: "hostnamectl set-hostname #{name}.jmsalles.casa"

    end
  end
end
